version: '3'
services:
  influxdb-source:
    image: "influxdb:1.8"
    volumes:
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
      - ./influxdb-source/:/var/lib/influxdb
      - ./:/tmp/backup-and-restore
    ports:
      - "8086:8086"

  influxdb-destination:
    image: "influxdb:1.8"
    volumes:
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
      - ./influxdb-destination/:/var/lib/influxdb
      - ./:/tmp/backup-and-restore
